
project_id = "nsxxzhhbcwzatvlulfyp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Renamed function (was process-albums-batch)
[functions.process-album-dispatcher]
verify_jwt = false

# Keep existing process-album-page function
[functions.process-album-page]
verify_jwt = false

# Keep existing process-track-page function
[functions.process-track-page]
verify_jwt = false

# Keep existing process-artists-batch function
[functions.process-artists-batch]
verify_jwt = false

# Keep existing monitor-pipeline function
[functions.monitor-pipeline]
verify_jwt = false

# Other existing functions
[functions.process-producers-batch]
verify_jwt = false

[functions.requeue-dead-letter]
verify_jwt = false

[functions.reset-expired-batches]
verify_jwt = false

[functions.discover-artists]
verify_jwt = false

[functions.identify-producers]
verify_jwt = false
