
project_id = "nsxxzhhbcwzatvlulfyp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Album processing functions
[functions.process-album-dispatcher]
verify_jwt = false

[functions.process-album-page]
verify_jwt = false

[functions.process-track-page]
verify_jwt = false

# New pipeline functions
[functions.discover-artists]
verify_jwt = false

[functions.monitor-pipeline]
verify_jwt = false

[functions.requeue-dead-letter]
verify_jwt = false

[functions.reset-expired-batches]
verify_jwt = false

